[project]
name = "arclet-alconna-avilla"
version = "0.1.4"
description = "Support Alconna for Avilla"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"},
]
dependencies = [
    "avilla-core>=1.0.0rc4",
    "arclet-alconna<2.0.0, >=1.2.0.7",
    "graiax-shortcut>=0.1.0",
    "graia-saya>=0.0.16",
    "arclet-alconna-graia>=0.6.2",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "AGPL-3.0"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.build]
includes = ["arclet/alconna/avilla"]